---

- name: Install packages
  hosts: all
  tasks:
    - name: YUM | Install packages
      ansible.builtin.dnf:
        name: "{{ packages }}"
        state: latest
      when: ansible_facts['os_family'] == "RedHat"

...
