---

- name: Update Linux System
  hosts: all
  tasks: 
    - name: YUM | Update System YUM
      yum: name=* state=latest update_cache=yes
      when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" or ansible_distribution == "Rocky"

    - name: APT | Update Cache APT
      apt: update_cache=yes
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

    - name: APT | Update System APT
      apt: name="*" state=latest
      when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"

...
